#!/usr/bin/env bash

# dotfiles

#  Copyright 2020 Jay Lamb, jaylamb@gmail.com
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

#File: git/hooks/pre-commit
#Description: Pre-commit hook

function message()
{
	echo $script_name: $1
}

function abort()
{
	if [[ "$#" -gt 0 ]]; then
		message "$1, aborting"
	fi

	exit 1
}

function whitespace_error_check()
{
	exec git -C $repository_dir diff-index --check --cached $against --
}

function main()
{
	script_dir=$( readlink -f "$0" ); readonly script_dir
	script_name=$( basename "$script_dir" ); readonly script_name
	hooks_dir=$( dirname "$script_dir" ); readonly hooks_dir
	repository_dir=$( readlink -f "$hooks_dir/../.." ); readonly repository_dir

	#Ensure the repository has at least one commit
	if git rev-parse --verify HEAD >/dev/null 2>&1
	then
		against=HEAD
	else
		against=$( git hash-object -t tree < /dev/null )
	fi

	whitespace_error_check
}

main "$@" 
